import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@/components/ui/themeToggle/ModeToggle";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationBar from "@/app/ui/navbar/navbar";
import Footer from "./ui/footer/footer";
import { Roboto_Condensed } from "next/font/google";
import AuthSessionProvider from "./components/sessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto_Condensed = Roboto_Condensed({
  variable: "--font-Roboto_Condensed",
  weight: "500",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Note X",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpeg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto_Condensed.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavigationBar />
          <AuthSessionProvider>
            {children}
          </AuthSessionProvider>
          <div className="fixed z-10 bottom-4 right-4">
            <ModeToggle />
          </div>
        </ThemeProvider>
        <div className="bg-[var(--background)]">
          <Footer />
        </div>
      </body>
    </html>
  );
}
